version: '3'

services: 
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 3000:3000
        working_dir: /app
        links:
            - mongodb

    mongodb:
        image: mongo
        volumes: 
            - mongodb:/data/db
        ports:
            - 27017:27017

volumes:
    mongodb: